### ISSUE TITLE
Support setting model through class kwargs

### ISSUE THREAD

**Issue by wookie184** [pydantic/pydantic-settings#110]
`pydantic.BaseModel` supports setting config through class kwargs:
```python
from pydantic import BaseModel
class Foo(BaseModel, extra='forbid'):
    pass
```

It would be nice for `pydantic_settings.BaseSettings` to also support this:
```python
from pydantic_settings import BaseSettings
class Foo(BaseSettings, env_file='.env'):
    pass
```
Currently an error is raised:
```python
Traceback (most recent call last):
  File "...\test.py", line 2, in <module>
    class Foo(BaseSettings, env_file='.env'):
  File "...\Lib\site-packages\pydantic\_internal\_model_construction.py", line 124, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
TypeError: Foo.__init_subclass__() takes no keyword arguments
```

This pydantic issue may be relevant: https://github.com/pydantic/pydantic/issues/6024

Thanks

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Thanks @wookie184 for this issue 🙏 

I've created a PR to support this.

**Comment by hramezani** [comment]
Support for setting `pydantic-settings` configs throgh kwargs added.
It will be available in next release.
