### ISSUE TITLE
Facing an AttributeError when using BaseSettings with RootModel

### ISSUE THREAD

**Issue by yak-toto** [pydantic/pydantic-settings#114]
Hello,

I'm migrating my application from pydantic v1 to v2 and I'm facing an issue with the BaseSettings, probably a bug.

## Steps to reproduce
installing pydantic==2.0.2 and pydantic-settings==2.0.1 in python 3.10.6.

I reproduce the scenario with this python script :

<h5 a><strong><code>main.py</code></strong></h5>

```py
from typing import List
from uuid import UUID

from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import RootModel, BaseModel

class Rule(BaseModel):
    id: UUID
    content: dict

Rules = RootModel[List[Rule]]

class Settings(BaseSettings):
    rules: Rules

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")

settings = Settings()
```

<h5 a><strong><code>.env</code></strong></h5>

```env
RULES='[]'
```

<h5 a><strong><code>Terminal output</code></strong></h5>

```sh
(venv) ~/test-pydantic-v2$ python main.py
Traceback (most recent call last):
  File "/home/glepape/test-pydantic-v2/main.py", line 22, in <module>
    settings = Settings()
  File "/home/glepape/test-pydantic-v2/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 62, in __init__
    **__pydantic_self__._settings_build_values(
  File "/home/glepape/test-pydantic-v2/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 150, in _settings_build_values
    return deep_update(*reversed([source() for source in sources]))
  File "/home/glepape/test-pydantic-v2/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 150, in <listcomp>
    return deep_update(*reversed([source() for source in sources]))
  File "/home/glepape/test-pydantic-v2/venv/lib/python3.10/site-packages/pydantic_settings/sources.py", line 572, in __call__
    data: dict[str, Any] = super().__call__()
  File "/home/glepape/test-pydantic-v2/venv/lib/python3.10/site-packages/pydantic_settings/sources.py", line 245, in __call__
    data[field_key] = self._replace_field_names_case_insensitively(field, field_value)
  File "/home/glepape/test-pydantic-v2/venv/lib/python3.10/site-packages/pydantic_settings/sources.py", line 199, in _replace_field_names_case_insensitively
    for name, value in field_values.items():
AttributeError: 'list' object has no attribute 'items'
```

With pydantic v1, I was not facing any issues.

A workaround would be to parse the env var by myself but it seems like a bug, please advise.

Selected Assignee: @hramezani

**Comment by yak-toto** [comment]
Thanks @hramezani
