### ISSUE TITLE
Configuring `secrets_dir` tries to parse `None` values as JSON

### ISSUE THREAD

**Issue by hofrob** [pydantic/pydantic-settings#122]
```py
import pathlib

import pydantic
import pydantic_settings

FOO_DEFAULT = ["one", "two"]


class Settings(pydantic_settings.BaseSettings):
    model_config = pydantic.ConfigDict(secrets_dir=pathlib.Path("/some/secret/dir/"))
    foo: list[str] = FOO_DEFAULT


if __name__ == '__main__':
    Settings()
```

There is no env var `FOO` in `.env` or the `secrets_dir`. So it should just use the default value. Without `model_config`, this runs fine.

Adding `model_config` will result in a JSON TypeError in `pydantic_settings.sources.PydanticBaseSettingsSource.prepare_field_value`:

```
Traceback (most recent call last):
  File "/project/path/main.py", line 15, in <module>
    Settings()
  File "/project/path/venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 62, in __init__
    **__pydantic_self__._settings_build_values(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/path/venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 150, in _settings_build_values
    return deep_update(*reversed([source() for source in sources]))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/path/venv/lib/python3.11/site-packages/pydantic_settings/main.py", line 150, in <listcomp>
    return deep_update(*reversed([source() for source in sources]))
                                  ^^^^^^^^
  File "/project/path/venv/lib/python3.11/site-packages/pydantic_settings/sources.py", line 285, in __call__
    return super().__call__()
           ^^^^^^^^^^^^^^^^^^
  File "/project/path/venv/lib/python3.11/site-packages/pydantic_settings/sources.py", line 237, in __call__
    field_value = self.prepare_field_value(field_name, field, field_value, value_is_complex)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/path/venv/lib/python3.11/site-packages/pydantic_settings/sources.py", line 87, in prepare_field_value
    return json.loads(value)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.3/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Process finished with exit code 1
```

- python version: 3.11.3
- OS: Ubuntu 22.04
- pydantic-settings | 2.0.1
- pydantic | 2.0.2
- pydantic-core | 2.1.2

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Thanks @hofrob for reporting this 🙏 

I think it is a duplicate of https://github.com/pydantic/pydantic-settings/issues/113 and has been fixed in https://github.com/pydantic/pydantic-settings/pull/118. This will be available in the next release.

Could you please test your example code with `main` branch and confirm the fix?

**Comment by hofrob** [comment]
Thank you for the quick response!

Yes, this fix solves the issue. Sorry for the duplicate!
