### ISSUE TITLE
Conflict between init value and env var

### ISSUE THREAD

**Issue by finswimmer** [pydantic/pydantic-settings#161]
Hey,

I'm trying to use `AliasChoices` for a `BaseSettings` Model. Everything works as expected, as long as I don't have set up any env vars and pass in the value on initializing an object or if the env var is set only.

But as soon as an env var is set and one of the other values in `AliasChoices` is used during initializing an object, pydantic raises an `ValidationError`.

Example:

```python
import os

from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings


class User(BaseSettings):
    first_name: str = Field(validation_alias=AliasChoices("first_name", "USER_FIRSTNAME"))


u1 = User(USER_FIRSTNAME="me")
u2 = User(first_name="me")

os.environ["USER_FIRSTNAME"] = "you"

# this works
u3 = User(USER_FIRSTNAME="me")

# this fails
u4 = User(first_name="me")

# Traceback (most recent call last):
#   File "/home/finswimmer/tmp/tests/minimal.py", line 15, in <module>
#     u4 = User(first_name="me")
#   File "/home/finswimmer/tmp/.venv/lib/python3.9/site-packages/pydantic_settings/main.py", line 71, in __init__
#     super().__init__(
#   File "/home/finswimmer/tmp/.venv/lib/python3.9/site-packages/pydantic/main.py", line 150, in __init__
#     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
# pydantic_core._pydantic_core.ValidationError: 1 validation error for User
# USER_FIRSTNAME
#   Extra inputs are not permitted [type=extra_forbidden, input_value='you', input_type=str]
#     For further information visit https://errors.pydantic.dev/2.0.3/v/extra_forbidden
```

My expectation for `u4` would be, that the `User` object is initiliazed with `first_name` is `me`.

fin swimmer

**Comment by hramezani** [comment]
Thanks @finswimmer for reporting this.

This is `Pydantic` behavior. By setting env variable `USER_FIRSTNAME` and passing `first_name` to setting initializer, You actually provide two values for `first_name` field. Then, as default extra is `forbid` in `pydantic-settings` you will get the error.

You can fix it by changing the default extra behavior to `ignore` by changing your example like:

```py
import os

from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class User(BaseSettings):
    model_config = SettingsConfigDict(extra='ignore')

    first_name: str = Field(validation_alias=AliasChoices("first_name", "USER_FIRSTNAME"))


u1 = User(USER_FIRSTNAME="me")
u2 = User(first_name="me")

os.environ["USER_FIRSTNAME"] = "you"

# this works
u3 = User(USER_FIRSTNAME="me")

# this fails
u4 = User(first_name="me")
```
