### ISSUE TITLE
Add `RootSettings`

### ISSUE THREAD

**Issue by rijenkii** [pydantic/pydantic-settings#200]
After making a [discussion](https://github.com/pydantic/pydantic/discussions/8293), [question](https://stackoverflow.com/questions/77600871/use-rootmodel-as-basesettings), and not getting any answers, I assume the functionality I'm looking for is not implemented, so I am making a feature request.

---

I want to use a following model for my settings:
```python
import pydantic

class Clustered(pydantic.BaseModel):
    is_clustered: typing.Literal[True]
    server_name: str


class NonClustered(pydantic.BaseModel):
    is_clustered: typing.Literal[False] = False

Settings = pydantic.RootModel[Clustered | NonClustered]
```

In pydantic v1 it was possible to do such a thing (I think):
```python
class Settings(pydantic.BaseSettings):
    __root__: Clustered | NonClustered
```

But in v2 `__root__` was removed, and multiple inheritance does not work:
```python
>>> class Settings(pydantic_settings.BaseSettings, pydantic.RootModel[NonClustered | Clustered]): pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 117, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
  File "/usr/local/lib/python3.12/site-packages/pydantic/root_model.py", line 50, in __init_subclass__
    raise PydanticUserError(
pydantic.errors.PydanticUserError: `RootModel` does not support setting `model_config['extra']`
```

---

What I assume needs to happen is `RootSettings` has to be added, so the following code can be written:
```python
Settings = pydantic_settings.RootSettings[Clustered | NonClustered]
```

**Comment by pavelrib** [comment]
@hramezani 
Actually, what was possible in pydantic v1 (given the example above):
```
Settings = typing.Union[Clustered, NonClustered]
pydantic.parse_obj_as(Settings)
```
Now fails when `is_clustered=False` in env var (I assume that it disregards the union). 
Any way around this, if we want to upgrade to pydantic v2?

**Comment by hramezani** [comment]
@pavelrib 
Have you tried [TypeAdapter](https://docs.pydantic.dev/latest/migration/#introduction-of-typeadapter)

**Comment by pavelrib** [comment]
@hramezani 
Thanks for the heads up, but can you please give an example of the usage in that case?
I've figured you meant probably:
```
Settings: TypeAdapter[typing.Union[Clustered, NonClustered]] = TypeAdapter(typing.Union[Clustered, NonClustered])
```
But what's the next step to evaluate Settings? All examples show validation with an actual object, but here the values should be implicitly read from env.

**Comment by pavelrib** [comment]
@hramezani Is there anything that I'm missing here?

**Comment by pavelrib** [comment]
@hramezani Is there any plan to add it in the near future? I've tried playing with different definitions and parsing methods to no avail.

**Comment by hramezani** [comment]
@pavelrib I don't think that I can add it shortly. I hope some contributors work on this but this can be a complex feature
