### ISSUE TITLE
issue with whitespaces in sub configs when parsing CLI args

### ISSUE THREAD

**Issue by AlessioM** [pydantic/pydantic-settings#368]
Whitespaces in Json Lists cause issue when parsing CLI args

Tested in pydantic_settings version 2.4.0

# Potential Fix
add a `.strip()` call at the end of the `_consume_comma` call here:
https://github.com/pydantic/pydantic-settings/blob/main/pydantic_settings/sources.py#L1178

# Example

```
#test.py
from pydantic import Field
from pydantic_settings import BaseSettings
from typing import List

class SubConfig(BaseSettings):
    a: int = Field()

class Config(
    BaseSettings,
    cli_parse_args=True
):
    fields: List[SubConfig] = Field()

if __name__ == "__main__":
    cfg = Config()
    print(cfg)
```
## Good Case
```
>> python test.py --fields '[{"a":1},{"a":2}]'
fields=[SubConfig(a=1), SubConfig(a=2)]
```
(note: no whitespace around comma in json)

## Broken Case
```
python test.py --fields '[{"a":1}, {"a":2}]'
Traceback (most recent call last):
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/sources.py", line 430, in __call__
    field_value = self.prepare_field_value(field_name, field, field_value, value_is_complex)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/sources.py", line 632, in prepare_field_value
    raise e
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/sources.py", line 629, in prepare_field_value
    value = self.decode_complex_value(field_name, field, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/sources.py", line 242, in decode_complex_value
    return json.loads(value)
           ^^^^^^^^^^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 13 (char 12)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alessio/prj/analysis_tools/isee_training/test.py", line 16, in <module>
    cfg = Config()
          ^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/main.py", line 145, in __init__
    **__pydantic_self__._settings_build_values(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/main.py", line 329, in _settings_build_values
    source_state = source()                
                   ^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/sources.py", line 1070, in __call__
    return super().__call__()
           ^^^^^^^^^^^^^^^^^^
  File "<<LOCAL_ENV>>lib/python3.11/site-packages/pydantic_settings/sources.py", line 432, in __call__
    raise SettingsError(
pydantic_settings.sources.SettingsError: error parsing value for field "fields" from source "CliSettingsSource"
```
(note: single whitespace right of comma in json)

**Comment by hramezani** [comment]
Thanks @AlessioM for reporting this issue and the suggestion for the fix. Would you like to create a PR?

@kschwab what do you think about the fix?

**Comment by hramezani** [comment]
> > Thanks @AlessioM for reporting this issue and the suggestion for the fix. Would you like to create a PR?
> > @kschwab what do you think about the fix?
> 
> I did already, see above

You need to create a PR in this repository. Also, don't forget to add a test for your fix.
Thanks.

**Comment by AlessioM** [comment]
Thanks for resovling this so quickly!
