### ISSUE TITLE
Setting a default value for ZoneInfo does not work

### ISSUE THREAD

**Issue by ac3673** [pydantic/pydantic-settings#480]
When setting a default value for ZoneInfo a different timezone is used. 

```python
Python 3.12.1 (main, Jan  8 2024, 05:53:39) [Clang 17.0.6 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydantic_settings
>>> from zoneinfo import ZoneInfo
>>> from pydantic_settings import BaseSettings
>>> class Test(BaseSettings):
...     tz: ZoneInfo = ZoneInfo("Europe/London")
... 
>>> Test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/acuthbert2/dev/ves/scripts/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 167, in __init__
    super().__init__(
  File "/home/acuthbert2/dev/ves/scripts/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Test
tz
  invalid timezone: :Asia/Shanghai [type=zoneinfo_str, input_value=':Asia/Shanghai', input_type=str]
>>> pydantic_settings.__version__
'2.6.1'
```

- pydantic-settings version: 2.6.1
- python version: 3.12.1
- platform: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

**Comment by hramezani** [comment]
It seems that you have a `tz` env variable that has the value of `:Asia/Shanghai`. the `:Asia/Shanghai` is an invalid timezone and this is the reason of the error.

**Comment by ac3673** [comment]
@hramezani I don't (or not that I know).

```python
>>> import os
>>> os.getenv("tz")
>>>
```


However naming the variable something other than `tz` does work correctly, so it does look to be something to do with my specific environment rather than a bug. Thanks

**Comment by ac3673** [comment]
Likely due to my environment, closing.
