### ISSUE TITLE
Error with EnvSettingsSource and alias_generator

### ISSUE THREAD

**Issue by AndreuCodina** [pydantic/pydantic-settings#501]
I have a nested model, and I need to get the environment variable `CUSTOM__ENVIRONMENT`, so I assign a value to it with:

```bash
export CUSTOM__ENVIRONMENT="MyValue"
```

And I use `EnvSettingsSource` to get the value. It works well, but when I add `alias_generator` to the models, I can't get the environment variable value.

```python
from pydantic import BaseModel
from pydantic.alias_generators import to_pascal
from pydantic_settings import (
    BaseSettings,
    EnvSettingsSource,
    PydanticBaseSettingsSource,
    SettingsConfigDict,
)


class CustomSettings(BaseModel):
    model_config = SettingsConfigDict(alias_generator=to_pascal)

    environment: str


class ApplicationSettings(BaseSettings):
    model_config = SettingsConfigDict(alias_generator=to_pascal, extra="ignore")

    custom: CustomSettings

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,  # noqa: ARG003
        env_settings: PydanticBaseSettingsSource,  # noqa: ARG003
        dotenv_settings: PydanticBaseSettingsSource,  # noqa: ARG003
        file_secret_settings: PydanticBaseSettingsSource,  # noqa: ARG003
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        env = EnvSettingsSource(settings_cls, env_nested_delimiter="__")
        return (env,)


print(ApplicationSettings())  # type: ignore[reportCallIssue]
```

**Error:**

```
Traceback (most recent call last):
  File "/workspaces/myproject/src/main.py", line 39, in <module>
    print(ApplicationSettings())  # type: ignore[reportCallIssue]
          ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/myproject/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 171, in __init__
    super().__init__(
  File "/workspaces/myproject/.venv/lib/python3.12/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ApplicationSettings
Custom.Environment
  Field required [type=missing, input_value={'environment': 'MyValue'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
```

**Package versions:**
pydantic-settings==2.7.0
pydantic==2.10.3

**Comment by hramezani** [comment]
Thanks, @AndreuCodina for reporting this.

`pydantic-settings` finds value for nested field based on field name(`custom`), delimiter(`__`), ... . right now it doesn't respect the nested model configurations. so it collects `{'Custom': {'environment': 'MyValue'}}` and passes it to pydantic for validation. that's why your example works if you remove the `model_config = SettingsConfigDict(alias_generator=to_pascal)` from nested model.

So, here is the workarounds:

* Remove the `model_config = SettingsConfigDict(alias_generator=to_pascal)` from nested model.
* Add `case_sensitive=True` to the `ApplicationSettings` and set the env variable like `Custom__Environment="MyValue"`
